export const productListData = [
    {title: "Super Mario Maker 2",
    id:"Super Mario Maker 2",
    price:11250,
    stock: 5,
    detailss: "Con este juego de Mario vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer. Interactuá con otros jugadores. Podrás disfrutar de una experiencia inigualable, ya que te permite jugar con tus amistades y compartir momentos inolvidables. Diversión sin fronteras. Podrás compartir cada juego con personas de todo el mundo, ya que es posible conectarse de manera online.",
    pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_757148-MLA40917205776_022020-O.webp",
    pictureUrl2:"https://assets.nintendo.com/image/upload/f_auto,q_auto,w_960,h_540/Legacy%20Videos/posters/NpdmQ2aTE6VOZQqF0P60yvH7GZ07v2H0",
    pictureUrl3:"https://static3.abc.es/media/tecnologia/2019/07/05/super-mario-maker2-kSG--620x349@abc.jpeg",
    pictureUrl4:"https://imagen.nextn.es/wp-content/uploads/2016/02/1602-01-Super-Mario-Maker-wallpaper-fondo-m%C3%B3vil-PC-01.jpg?strip=all&lossy=1&ssl=1",
    Url2: "https://http2.mlstatic.com/resources/frontend/ft-extended-v00/assets/vectorial/default.svg",
    details: "Plataforma: Nintendo Switch",
    details2: "Es multijugador: Sí",
    details3: "Tamaño del archivo: 2.8 GB",
    details4: "Formato: Físico",
    details5: "Es en línea: Sí"},
    
    {title: "Super Mario 3D World",
    id:"Super Mario 3D World",
    price:11899,
    detailss: "Con este juego de Mario vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer. Interactuá con otros jugadoresPodrás disfrutar de una experiencia inigualable.",
    stock: 4,
    pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_940603-MLA44886780516_022021-O.webp",
    pictureUrl2:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_supermario3dworldandbowsersfury/NSwitch_SuperMario3DWorldAndBowsersFury_01.jpg",
    pictureUrl3:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_supermario3dworldandbowsersfury/NSwitch_SuperMario3DWorldAndBowsersFury_02.jpg",
    pictureUrl4:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_supermario3dworldandbowsersfury/NSwitch_SuperMario3DWorldAndBowsersFury_03.jpg",
    details: "Plataforma: Nintendo Switch",
    details2: "Es multijugador: Sí",
    details3: "Tamaño del archivo: 215 GB",
    details4: "Formato: Físico",
    details5: "Es en línea: No"},
    
    {title: "Mario Party SuperStars",
    id:"Mario Party SuperStars",
    price:11938,
    detailss: "Con este juego de Mario vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer. Interactuá con otros jugadoresPodrás disfrutar de una experiencia inigualable.",
    stock: 6,
    pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_738842-MLA48119679478_112021-O.webp",
    pictureUrl2:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_mariopartysuperstars/NSwitch_MarioPartySuperStars_01.jpg",
    pictureUrl3:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_mariopartysuperstars/NSwitch_MarioPartySuperStars_02.jpg",
    pictureUrl4:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_mariopartysuperstars/NSwitch_MarioPartySuperStars_03.jpg",
    details: "Plataforma: Nintendo Switch",
    details2: "Es multijugador: Sí",
    details3: "Tamaño del archivo: 20 GB",
    details4: "Formato: Físico",
    details5: "Es en línea: Sí"},
    
    {title: "Super Smash Bros",
    id:"Super Smash Bros  Ultimate",
    price:12325,
    detailss: "Con este juego de Mario vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer. Interactuá con otros jugadoresPodrás disfrutar de una experiencia inigualable.",
    stock: 10,
    pictureUrl: "https://www.cjs-cdkeys.com/product_images/img/o/17012.jpg",
    pictureUrl2:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_supersmashbrosultimate/NSwitch_SuperSmashBrosUltimate_01.jpg",
    pictureUrl3:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_supersmashbrosultimate/NSwitch_SuperSmashBrosUltimate_02.jpg",
    pictureUrl4:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_supersmashbrosultimate/NSwitch_SuperSmashBrosUltimate_04.jpg",
    details: "Plataforma: Nintendo Switch",
    details2: "Es multijugador: Sí",
    details3: "Tamaño del archivo: 8 GB",
    details4: "Formato: Físico",
    details5: "Es en línea: Sí"},
    
    {title: "Zelda Link's Awakening",
    id:"Zelda Link's Awakening",
    price:10499,
    detailss: "Los juegos de la franquicia The Legend of Zelda marcaron un antes y después en el género de aventura. Convertite en Link para vencer a los villanos que hicieron de un pacífico reino un lugar inmerso en las tinieblas.",
    stock: 20,
    pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_968049-MLA40927047075_022020-O.webp",
    pictureUrl2:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_thelegendofzeldalinksawakening/NSwitch_TheLegendofZeldaLinksAwakening_01.png",
    pictureUrl3:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_thelegendofzeldalinksawakening/NSwitch_TheLegendofZeldaLinksAwakening_02.png",
    pictureUrl4:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_thelegendofzeldalinksawakening/NSwitch_TheLegendofZeldaLinksAwakening_03.png",
    details: "Plataforma: Nintendo Switch",
    details2: "Es multijugador: Sí",
    details3: "Tamaño del archivo: 30 GB",
    details4: "Formato: Físico",
    details5: "Es en línea: No"},
    
    {title: "Animal Crossing",
    id:"Animal Crossing",
    price:12250,
    stock: 2,
    detailss: "Con este juego de Mario vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer. Interactuá con otros jugadores. Podrás disfrutar de una experiencia inigualable, ya que te permite jugar con tus amistades y compartir momentos inolvidables. Diversión sin fronteras. Podrás compartir cada juego con personas de todo el mundo, ya que es posible conectarse de manera online.",
    pictureUrl: "https://m.media-amazon.com/images/I/81QvUXy2qpL._AC_SL1500_.jpg",
    pictureUrl2:"https://assets.nintendo.com/image/upload/f_auto,q_auto,w_960,h_540/Legacy%20Videos/posters/NpdmQ2aTE6VOZQqF0P60yvH7GZ07v2H0",
    pictureUrl3:"https://static3.abc.es/media/tecnologia/2019/07/05/super-mario-maker2-kSG--620x349@abc.jpeg",
    pictureUrl4:"https://imagen.nextn.es/wp-content/uploads/2016/02/1602-01-Super-Mario-Maker-wallpaper-fondo-m%C3%B3vil-PC-01.jpg?strip=all&lossy=1&ssl=1",
    Url2: "https://http2.mlstatic.com/resources/frontend/ft-extended-v00/assets/vectorial/default.svg",
    details: "Plataforma: Nintendo Switch",
    details2: "Es multijugador: Sí",
    details3: "Tamaño del archivo: 2.8 GB",
    details4: "Formato: Físico",
    details5: "Es en línea: Sí"},
    
    {title: "Metroid Dread",
    id:"Metroid Dread",
    price:14899,
    detailss: "Con este juego de Mario vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer. Interactuá con otros jugadoresPodrás disfrutar de una experiencia inigualable.",
    stock: 9,
    pictureUrl: "https://m.media-amazon.com/images/I/8176HX52haL._AC_SL1500_.jpg",
    pictureUrl2:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_supermario3dworldandbowsersfury/NSwitch_SuperMario3DWorldAndBowsersFury_01.jpg",
    pictureUrl3:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_supermario3dworldandbowsersfury/NSwitch_SuperMario3DWorldAndBowsersFury_02.jpg",
    pictureUrl4:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_supermario3dworldandbowsersfury/NSwitch_SuperMario3DWorldAndBowsersFury_03.jpg",
    details: "Plataforma: Nintendo Switch",
    details2: "Es multijugador: Sí",
    details3: "Tamaño del archivo: 215 GB",
    details4: "Formato: Físico",
    details5: "Es en línea: No"},
    
    {title: "Monster hunter",
    id:"Monster hunter",
    price:8938,
    detailss: "Con este juego de Mario vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer. Interactuá con otros jugadoresPodrás disfrutar de una experiencia inigualable.",
    stock: 2,
    pictureUrl: "https://m.media-amazon.com/images/I/91FX+p6qDbS._AC_SL1500_.jpg",
    pictureUrl2:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_mariopartysuperstars/NSwitch_MarioPartySuperStars_01.jpg",
    pictureUrl3:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_mariopartysuperstars/NSwitch_MarioPartySuperStars_02.jpg",
    pictureUrl4:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_mariopartysuperstars/NSwitch_MarioPartySuperStars_03.jpg",
    details: "Plataforma: Nintendo Switch",
    details2: "Es multijugador: Sí",
    details3: "Tamaño del archivo: 20 GB",
    details4: "Formato: Físico",
    details5: "Es en línea: Sí"},
    
    {title: "Luigi's Mansion",
    id:"Luigi's Mansion",
    price:13325,
    detailss: "Con este juego de Mario vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer. Interactuá con otros jugadoresPodrás disfrutar de una experiencia inigualable.",
    stock: 30,
    pictureUrl: "https://m.media-amazon.com/images/I/81cHm50auZL._SL1500_.jpg",
    pictureUrl2:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_supersmashbrosultimate/NSwitch_SuperSmashBrosUltimate_01.jpg",
    pictureUrl3:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_supersmashbrosultimate/NSwitch_SuperSmashBrosUltimate_02.jpg",
    pictureUrl4:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_supersmashbrosultimate/NSwitch_SuperSmashBrosUltimate_04.jpg",
    details: "Plataforma: Nintendo Switch",
    details2: "Es multijugador: Sí",
    details3: "Tamaño del archivo: 8 GB",
    details4: "Formato: Físico",
    details5: "Es en línea: Sí"},
    
    {title: "Kirby y la Tierra Olvidada",
    id:"Kirby y la Tierra Olvidada",
    price:10499,
    detailss: "Los juegos de la franquicia The Legend of Zelda marcaron un antes y después en el género de aventura. Convertite en Link para vencer a los villanos que hicieron de un pacífico reino un lugar inmerso en las tinieblas.",
    stock: 60,
    pictureUrl: "https://m.media-amazon.com/images/I/81apvVCVNNL._AC_SL1500_.jpg",
    pictureUrl2:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_thelegendofzeldalinksawakening/NSwitch_TheLegendofZeldaLinksAwakening_01.png",
    pictureUrl3:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_thelegendofzeldalinksawakening/NSwitch_TheLegendofZeldaLinksAwakening_02.png",
    pictureUrl4:"https://fs-prod-cdn.nintendo-europe.com/media/images/06_screenshots/games_5/nintendo_switch_6/nswitch_thelegendofzeldalinksawakening/NSwitch_TheLegendofZeldaLinksAwakening_03.png",
    details: "Plataforma: Nintendo Switch",
    details2: "Es multijugador: Sí",
    details3: "Tamaño del archivo: 30 GB",
    details4: "Formato: Físico",
    details5: "Es en línea: No"},
    
]

